# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================
detector:
  rpcs:
    - chain-name: ethereum-mainnet
      url: https://1rpc.io/eth
    - chain-name: ethereum-testnet-sepolia
      url: https://1rpc.io/sepolia
    - chain-name: ethereum-testnet-sepolia-base-1
      url: https://sepolia.base.org
    - chain-name: ethereum-testnet-sepolia-arbitrum-1
      url: https://arbitrum-sepolia.drpc.org

relayer:
  rpcs:
    - chain-name: ethereum-mainnet
      url: https://1rpc.io/eth
    - chain-name: ethereum-testnet-sepolia
      url: https://1rpc.io/sepolia
    - chain-name: ethereum-testnet-sepolia-base-1
      url: https://sepolia.base.org
    - chain-name: ethereum-testnet-sepolia-arbitrum-1
      url: https://arbitrum-sepolia.drpc.org


