# ==========================================================================
# CRE WORKFLOW SETTINGS FILE
# =========================================================================

detector:
  user-workflow:
    workflow-name: "cctp-detector"
  workflow-artifacts:
    workflow-path: "./detector.ts"
    config-path: "./config.json"
    secrets-path: "../secrets.yaml"

# ==========================================================================
relayer:
  user-workflow:
    workflow-name: "cctp-relayer"
  workflow-artifacts:
    workflow-path: "./relayer.ts"
    config-path: "./config.json"
    secrets-path: "../secrets.yaml"
    